apiVersion: v1
kind: Pod 
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:    
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
        - name: foo
          mountPath: /etc/foo
          readOnly: true
  volumes: 
    - name: secret-volume
      secret: 
        secretName: test-secret
    - name: foo
      secret: 
        secretName: mysecret
        items: 
          - key: username
            path: my-group/my-username