#! /usr/bin/env bash
alias ll='ls -l'
alias jspp-kubectl='kubectl --kubeconfig $HOME/.kube/config.fuli -n jspp'
alias grep='grep -v grep | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias cat='bat --tabs 4 --theme gruvbox-dark -p --paging=never '
alias nocat='bat --tabs 4 --theme gruvbox-dark -p -n --paging=never'
alias python='/usr/local/bin/python3.7'
alias pip='/usr/local/bin/pip3.7'
alias ag='/usr/local/bin/ag --color-match 35:48 --color-path 6:37 '
alias rg=$HOME'/.cargo/bin/rg --ignore-file=$HOME/.gitignore --colors "match:fg:magenta" --colors "line:bg:black" '
alias fd='/usr/local/bin/fd --ignore-file=$HOME/.gitignore '
alias code='/usr/local/bin/code 2>/dev/null '
alias ls=$HOME'/.cargo/bin/exa -s modified'
alias gawk='/usr/local/bin/gawk -i $HOME/Workdata/goland/src/jspp/testgo/shell/awk/lib.awk '

export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"
export TESTGOPATH=$HOME/Workdata/goland/src/jspp/testgo
export AWKPATH=/usr/local/bin/gawk
export GO15VENDOREXPERIMENT=1
export GO_JSPP_WORKSPACE=Workdata/goland/src/jspp
export GOPATH=$HOME/Workdata/goland
export GOFLAGS=""
export GOPRIVATE=code.jspp.com
export GOOS=darwin
export GOARCH=amd64
export GOROOT="$HOME/Workdata/goland/go1.21.12"
export CGO_ENABLED=1
export GOMAXPROCS=12
export CARGO_NET_GIT_FETCH_WITH_CLI=true
export BAT_PAGER="less -RF"
export ELECTRON_MIRROR="http://cdn.npm.taobao.org/dist/electron/"
export FZF_COMPLETION_TRIGGER='**'
export TERM="xterm-256color"
export GIPHY_API_KEY=xVXd8j7UxP8Lvn8Dn1aLjLAd5EHYGE31
export GIPHY_RATING=pg-13
export IDEA_LAUNCHER_DEBUG=true
export C_INCLUDE_PATH=
export CPLUS_INCLUDE_PATH=
export LD_LIBRARY_PATH=
export LIBRARY_PATH=
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export FZF_DEFAULT_COMMAND="fd --exclude={.git,.idea,.vscode,.sass-cache,node_modules,build} --type file"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse "
export KUBEBUILDER_ASSETS="$HOME/Library/Application Support/io.kubebuilder.envtest/k8s/1.22.1-darwin-amd64"
export VIMCONFIG=$HOME/Workdata/nvim-config
export VIMDATA=$HOME/.local/share/nvim
export ANDROID_HOME="$HOME/Library/Android/sdk"
export JAVA_HOME="$HOME/Library/Java/JavaVirtualMachines/openjdk-8u442-b06-mac-x64/jdk1.8.0_442.jdk/Contents/Home"
export HISTFILE=$HOME/.zsh_history
export ENVTEST_INSTALLED_ONLY=true
export KUBEBUILDER_ATTACH_CONTROL_PLANE_OUTPUT=true
export HISTCONTROL=ignoredups
export HISTSIZE=2000000
export SAVEHIST=2000000
export PROMPT_COMMAND='history -a'
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE="ls:history"
export GIN_MODE=release
export ISABLE_MAGIC_FUNCTIONS=true
export RUST_BACKTRACE=0
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'
export JMETER_HOME=/usr/local/apache-jmeter-5.1.1
export HOMEBREW_NO_AUTO_UPDATE=
export HOMEBREW_NO_INSTALL_CLEANUP=
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=
export PYTHONDONTWRITEBYTECODE=1
export CLASSPAHT=".:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
export SDKROOT=$(xcrun --show-sdk-path)

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin":$PATH
export PATH="$HOME/.rvm/bin":$PATH
export PATH="$HOME/.composer/vendor/bin":$PATH
export PATH="$HOME/.rvm/bin":$PATH
export PATH="$HOME/Downloads":$PATH
export PATH="$HOME/.cargo/bin":$PATH
export PATH="$HOME/.tiup/bin:$PATH"
export PATH="$HOME/Workdata/goland/bin":$PATH
export PATH="$MAVEN_HOME/bin":$PATH
export PATH="$JAVA_HOME/bin":$PATH
export PATH="$GOPATH/bin":$PATH
export PATH="$GOROOT/bin":$PATH
export PATH="/usr/local/sbin":$PATH
export PATH="/usr/local/opt/openssl/bin":$PATH
export PATH="/usr/local/opt/qt/bin:$PATH"
export PATH="/usr/local/opt/make/libexec/gnubin":$PATH
export PATH="/Applications/SwitchHosts.app/Contents/MacOS":$PATH
export PATH="/usr/local/opt/rabbitmq/sbin/:"$PATH
export PATH="/usr/local/oh-command-line-tools/bin":$PATH
export PATH="/usr/local/command-line-tools/bin":$PATH
export PATH="/usr/local/Cellar/ctags/5.8_2/bin":$PATH
export PATH="/usr/local/opt/gnu-getopt/bin":$PATH
export PATH="/usr/local/opt/gnu-indent/libexec/gnubin":$PATH
export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
export PATH="/usr/local/Cellar/kubernetes-cli/1.28.2/bin":$PATH
export PATH="/usr/local/opt/binutils/bin:$PATH"
export PATH="/usr/local/command-line-tools/bin:$PATH"
export PATH="/usr/local/Cellar/bash/5.2.15/bin":$PATH
export PATH="/usr/local/Cellar/cocoapods/1.14.3/bin":$PATH
export PATH="/usr/local/Cellar/ruby/3.3.4/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/3.3.0/bin:$PATH"

ZSH_THEME_GIT_PROMPT_PREFIX="%{$reset_color%}%{$fg[green]%}["
ZSH_THEME_GIT_PROMPT_SUFFIX="]%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}*%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""

MACOSX_SDK="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
export LIBRARY_PATH="$MACOSX_SDK/usr/lib"
export CPATH="$MACOSX_SDK/usr/include"

a() {
  $TESTGOPATH/shell/start.sh "$@"
}

export WORDCHARS='*?_-[]~&;!#$%^(){}<>'
# bind 'set skip-completed-text on'
# bind 'set word-separators " /\\"'  # 自定义分隔符（空格、斜杠、引号等）
# bindkey '^[^[[D' backward-word  # Option + ←
# bindkey '^[^[[C' forward-word   # Option + →

source $HOME/.cargo/env
source $HOME/.local_config
