# shellcheck disable=SC2206,2034,1091,2086,1090

export DISABLE_MAGIC_FUNCTIONS="true"
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/.tiup/bin:$PATH
export NVM_DIR=$HOME/.nvm

ZSH_THEME="amuse"

autoload -Uz compinit
compinit

plugins=(
    git
    extract
    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
    golang
    zsh-autopair
)

fpath=($HOME/.docker/completions $fpath)

source $ZSH/oh-my-zsh.sh
source $HOME/.bashrc
source $HOME/.fzf.zsh
source $HOME/.cargo/env
source ${HOME}/.iterm2_shell_integration.zsh
source /usr/local/etc/profile.d/z.sh
source /usr/local/etc/profile.d/bash_completion.sh
source /usr/local/opt/nvm/nvm.sh
source /usr/local/opt/nvm/etc/bash_completion.d/nvm
source /usr/local/etc/profile.d/autojump.sh
source <(kubectl completion zsh)

setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
