# shellcheck disable=SC2206,2034,1091,2086,1090

export DISABLE_MAGIC_FUNCTIONS="true"
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/.tiup/bin:$PATH
export NVM_DIR=$HOME/.nvm

ZSH_THEME="amuse"
autoload -Uz compinit
compinit

plugins=(
    git
    golang
    extract
    autojump
    iterm2
    brew
    command-not-found
    encode64
    fzf
    gnu-utils
    vscode

    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-autopair
)

zstyle :omz:plugins:iterm2 shell-integration yes

fpath=($HOME/.docker/completions $fpath)
source $(brew --prefix)/etc/profile.d/z.sh
source $(brew --prefix)/etc/profile.d/bash_completion.sh
source $(brew --prefix)/opt/nvm/nvm.sh
source $(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm

HB_CNF_HANDLER="$(brew --repository)/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
    source "$HB_CNF_HANDLER";
fi
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'
source $HOME/.fzf.zsh
source $HOME/.cargo/env
source $HOME/.iterm2_shell_integration.zsh
source $ZSH/oh-my-zsh.sh
source $HOME/.bashrc

source <(kubectl completion zsh)

setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jim/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
