runServer:
	@php simple/tcp_server.php

runClient:
	@php simple/tcp_client.php

runServerMultiClient:
	@php simple/server_multi_client.php

runSwooleServerMultiClient:
	@php simple/swoole_server_multi_client.php

.PHONY: runServer