// Code generated by cmd/cgo; DO NOT EDIT.

//line /Users/jim/Workdata/goland/src/jspp/testgo/main.go:1:1
package main

/*
#include "stdio.h"
void test(int n) {
    char dummy[10240];
    printf("in c test func iterator %d\n", n);
    if(n <= 0) {
    return;
    }
    dummy[n] = '\a';
    test(n-1);
}
#cgo CFLAGS: -g
*/
import _ "unsafe"

func main() {
	( /*line :19:2*/_Cfunc_test /*line :19:7*/)( /*line :19:9*/_Ctype_int /*line :19:14*/(2))
}
